server {
    listen 8080;
    
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    location /api/orders {
        proxy_pass http://host.docker.internal:5027;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/inventory {
        proxy_pass http://host.docker.internal:5293;
        proxy_set_header Host $host;
    }

    location /api/products {
        proxy_pass http://host.docker.internal:5298;
        proxy_set_header Host $host;
    }

    location /api/prices {
        proxy_pass http://host.docker.internal:5012;
        proxy_set_header Host $host;
    }

    location /api/search {
        proxy_pass http://host.docker.internal:5100;
        proxy_set_header Host $host;
    }

    location /health/ {
        proxy_pass http://host.docker.internal:$arg_port/health;
    }
}
